name: index-binaries
run-name: Creating html index pages for binary releases
on: [push]
jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          echo "cwd"
          ls
          echo "root"
          ls /
          echo "workspace"
          ls ${{ github.workspace }}
