name: index-binaries
run-name: Creating html index pages for binary releases
on: [push]
jobs:
	create-pages:
		runs-on: ubuntu-latest
		steps:
			- run: echo 'Indexing'
			- run: cd public/deb/
			- run: echo "<html><body><div align=\"center\"><h1>Archive of BookThief+Liesel versions</h1><br><h3>Directory Listing:</h3><br><br>" > ./index.html
			- run: for i in `ls`; do if [ $i == 'index.html' ]; then   echo "skipping.."; else   space=" ";   nothing="";   filetitle="${i/_amd64/$nothing}";   filetitle="${filetitle/.deb/$nothing}";   filetitle="${filetitle/_/$space}";   filetitle="${filetitle/-/$space}"   echo "<a href='$i'>$filetitle</a><br>" >> ./index.html; fi; done
			- run: echo "</div></body></html>" >> ./index.html
			- run: cd ../win64
			- run: echo "<html><body><div align=\"center\"><h1>Archive of BookThief+Liesel versions (Windows)</h1><br><h3>Directory Listing:</h3><br><br>" > ./index.html
			- run: for i in `ls`; do if [ $i == 'index.html' ]; then   echo "skipping.."; else   echo "<a href='$i'>$i</a><br>" >> ./index.html;   echo "<html><body><div align=\"center\"><h1>Archive of BookThief+Liesel versions (Windows) [$i]</h1><br><h3>Directory Listing:</h3><br><br>" > ./$i/index.html;   for x in `ls $i`; do     if [ $x == 'index.html' ]; then       echo "skipping..";     else       echo "<a href='$x'>$x</a><br>" >> ./$i/index.html;     fi;   done; fi; done
